spring:
  datasource:
    url: jdbc:h2:file:~/data/banque
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
        ddl-auto : create
    show-sql: true
  sql:
    init:
      mode: always